# Generated by Django 3.2.1 on 2021-05-25 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='time'),
            preserve_default=False,
        ),
    ]
