# Generated by Django 3.2.1 on 2021-05-25 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_test_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
