# Generated by Django 3.2.1 on 2021-05-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_test_convert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
