# Generated by Django 3.2.1 on 2021-05-27 15:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_convert_pub_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convert',
            options={'ordering': ['-pub_time'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterField(
            model_name='convert',
            name='currency',
            field=models.CharField(max_length=5, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='convert',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='convert',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Значение'),
        ),
    ]
