# Generated by Django 3.2.1 on 2021-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210527_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=5, verbose_name='Валюта')),
                ('password', models.CharField(max_length=5, verbose_name='Валюта')),
            ],
        ),
    ]
