# Generated by Django 3.2.1 on 2021-06-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210602_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
