# Generated by Django 3.2.1 on 2021-06-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210602_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
