# Generated by Django 3.2.1 on 2021-06-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_exchangerate_exchange_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exchange_rate',
            new_name='ExchangeRate',
        ),
    ]
